# Generated by Django 2.2.4 on 2023-03-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0002_auto_20230328_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
    ]
