# Generated by Django 2.2.4 on 2023-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0003_auto_20230322_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
