# Generated by Django 3.2.18 on 2023-03-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20230321_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Null'),
        ),
    ]
