# Generated by Django 2.2.4 on 2023-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
